### ISSUE TITLE
Which device ?

### ISSUE THREAD

**Issue by jbfuzier** [MarcG046/timebox#1]
Hi,

For which device is your code made ? 
It does not work with my timebox **mini** whereas ScR4tCh's cli works.

It seems that your package code dans ScR4tCh's cli does not follow the same protocol : 

To display clock : 

ScR4tCh code send : ['01', '04', '00', '45', '00', '49', '00', '02']

Yours send : ['01', '05', '00', '45', '00', '03', '04', '4b', '00', '02']

The difference  '03', '04' is according to your protocol documentation related to 12/24h time format. So either we are not using the same device or the 12/24 option is optional and then the problem is elsewhere...

**Comment by DaveDavenport** [comment]
I have the mini and the above worked for me after the following patch:
https://github.com/DaveDavenport/timebox/commit/d258587269022a7b61c3338a590aba8d3be0004e

**Comment by jbfuzier** [comment]
Thanks, I will try with your patch.

**Comment by jbfuzier** [comment]
Thanks @DaveDavenport , it is working on timebox mini with your patch :)
