### ISSUE TITLE
Commands to turn on/of the radio

### ISSUE THREAD

**Issue by bigboss97** [MarcG046/timebox#2]
In the protocol documentation, it states: the radio command is followed by 0x00/0x01 as switch.
In my experiments, I had to swap the 0x01 and 0x00 bytes to switch:
01 05 00 05 03 04 00 0b 00 02 (radio on)
01 05 00 05 00 03 04 0b 00 02 (radio off, BT disconnected)
Are you using the same messages?

**Comment by fspralja** [comment]
Hi, hey what protocol specification, I would like to see that, didn't realise there is anything available ;)

**Comment by bigboss97** [comment]
No, divoom keeps it closed. We are more or less "guessing". But welcome to the club  :-)
Have a look here:
https://github.com/MarcG046/timebox/blob/master/doc/protocol.md
I was only able to get some of the commands working. I'm still waiting for MarcG046's response.

**Comment by fspralja** [comment]
Ah, ofc, sorr I misunderstood you, hoped there was something official :D

**Comment by bigboss97** [comment]
I've created a web site to generate the message string. Basically it helps you to calculate the length and check sum:
http://tiny.cc/go2tbmsg
You can copy the HEX string and send it with a BT terminal.
Now you can play around with the message. For instance, if you increase F3 of following message you will see the display changing  :-)
`010500450304004b0002`
btw, I still haven't got any message of a different length working.

**Comment by bigboss97** [comment]
Finally, I got it right. I managed to send an image to the box, hooray!
Thanks for the document. I don't know how you got the protocol, but that's GREAT! :-)
(did you use anything like wireshark to listen to the messages?)

I created a tutorial for people who want to experiment with messages:
https://youtu.be/AxLrxUsjFd8
